### ISSUE TITLE
Domain Access Control Register Offsets

### ISSUE THREAD

**Issue by astrelsky** [RusPiRo/ruspiro-register#6]
I happened to notice that the offset for D0..D15 are all 0. While I don't know much about the mmu yet as I'm actually learning how to set it up from looking at ruspiro-boot, this doesn't seem to be correct.

https://github.com/RusPiRo/ruspiro-register/blob/df74072234d4e1319ea6ef10a57fb8bdd836c8d2/src/system/aarch32/dacr.rs#L18-L40
etc, etc.

**Comment by 2ndTaleStudio** [comment]
Hi,

well spotted. You are absolutely right. Thx does not make any sense that all offsets are 0. This seem to be a typical copy+paste error. Will be fixed soon.
